### ISSUE TITLE
Incompatibility with CC: Tweaked 1.114.0

### ISSUE THREAD

**Issue by eliasjurkeit** [xiewuzhiying/VS-Addition#63] opened 2024-11-19 16:43 UTC
### Mod Name

CC: Tweaked

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

Forge Version: 47.3.12

CC: Tweaked Version: 1.114.0

When right clicking on a computer of CC: Tweaked the game crashes.

### Issue reproduction

1. Create / Login to a world
2. Place down a computer from CC: Tweaked
3. Right click it with an empty hand

### Logs

https://mclo.gs/EP2YSJR

**Comment by eliasjurkeit** [comment] 2024-11-19 16:46
Reverting CC: Tweaked back to 1.113.1 fixes the issue.

**Comment by xiewuzhiying** [comment] 2024-11-19 18:03
Duplicate of #61

**Closed as completed by xiewuzhiying** 2024-11-19 18:03 UTC
